#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use App\UpSlim;

// -----------------------------------------------------------------------------
// To help the built-in PHP dev server, check if the request was actually for
// something which should probably be served as a static file
// -----------------------------------------------------------------------------
if (PHP_SAPI === 'cli-server' && $_SERVER['SCRIPT_FILENAME'] !== __FILE__) {
    return false;
}

require __DIR__ . '/vendor/autoload.php';

// -----------------------------------------------------------------------------
// Instantiate the app
// -----------------------------------------------------------------------------
if (!file_exists(__DIR__ . '/bootstrap/settings.php'))
    throw new \Exception('File settings not exists. Create one in the bootstrap folder at the root of your project.');

$settings = require_once(__DIR__ . '/bootstrap/settings.php');
$appUpSlim = new \App\UpSlim($settings);
\App\UpSlim::setInstance($appUpSlim);


$application = new Application(UpSlim::getName(), UpSlim::getVersion());

App\Console\Boot::setApplication($application);
App\Console\Boot::bootCommand();

$application->run();