<?php
/**
 * Created by PhpStorm.
 * User: dilsonrabelo
 * Date: 15/09/16
 * Time: 16:25
 */

namespace Tests\Auth;


use App\Mapper\ServiceUser;
use Doctrine\ODM\MongoDB\DocumentManager;

class AuthenticateServiceTest
{

    /**
     * @var DocumentManager
     */
    private $dm;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->dm = $this->_ci->get("database");
}

    /**
     * @test
     */
    public function shouldCreateUser() {
        $service = new ServiceUser();
        $service->privateKey = "";
        $service->publicKey = "";
        $service->secret = "";

        $this->dm->persist($service);
        $this->dm->flush();

        $userSelect = $this->dm->getRepository(User::class)->findBy(['username' => 'user']);

        $this->assertInstanceOf(User::class, $userSelect[0]);
        $this->assertEquals("nonepassword", $user->password);
    }

}