<?php

namespace Tests\Auth;

use App\Mapper\User;
use Doctrine\ODM\MongoDB\DocumentManager;
use Tests\BaseUnitTests;

class AuthenticateTest extends BaseUnitTests
{
    /**
     * @var DocumentManager
     */
    private $dm;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->dm = $this->_ci->get("database");
    }

    /**
     * @test
     */
    public function shouldCreateUser() {
        $user = new User();
        $user->username = "user";
        $user->password = "nonepassword";

        $this->dm->persist($user);
        $this->dm->flush();

        $userSelect = $this->dm->getRepository(User::class)->findBy(['username' => 'user']);

        $this->assertInstanceOf(User::class, $userSelect[0]);
        $this->assertEquals("nonepassword", $user->password);
    }


    /**
     * @test
     * @depends shouldCreateUser
     */
    public function shouldExcludeUser() {
        $userSelect = $this->dm->getRepository(User::class)->findBy(['username' => 'user']);
        $this->dm->remove($userSelect[0]);
        $this->dm->flush();
    }

}