<?php
/**
 * Created by PhpStorm.
 * User: dilsonrabelo
 * Date: 30/08/16
 * Time: 08:55
 */

namespace Tests\JWT;

use Namshi\JOSE\SimpleJWS;
use Tests\BaseTests;

class TokenTests extends BaseTests
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function shouldGenerateToken() {
        $payload = [
            'sub' => '1234567890',
            'name' => 'John Doe',
            'admin' => true
        ];

        $header = [
            'alg' => 'HS256',
            'typ' => 'JWT'
        ];

        $jwt = new SimpleJWS($header);
        $jwt->setPayload($payload);
        $jwt->sign('secret');

        $this->assertEquals($jwt->getTokenString(), 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ');

    }

}