<?php

namespace Tests\JWT;

use App\Facilitator\App\JWTFacilitator;
use Namshi\JOSE\JWS;
use Namshi\JOSE\SimpleJWS;
use Tests\BaseUnitTests;

class TokenTest extends BaseUnitTests
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function shouldGenerateToken() {
        $payload = [
            'sub' => 1234567890,
            'name' => 'John Doe',
            'admin' => true,
            'iat' => 1472560284,
        ];

        $header = [
            'alg' => 'HS256',
            'typ' => 'JWT'
        ];

        $token = JWTFacilitator::createToken($header, $payload, 'password');

        $this->assertTrue(JWTFacilitator::validateToken($token, 'password'));
    }

    /**
     * @test
     */
    public function shouldValidateTokenExpired() {
        $dateTime = new \DateTime('yesterday');

        $payload = [
            'sub' => 1234567890,
            'name' => 'John Doe',
            'admin' => true,
            'iat' => 1472560284,
            'exp' => $dateTime->getTimestamp()
        ];

        $header = [
            'alg' => 'HS256',
            'typ' => 'JWT'
        ];

        $token = JWTFacilitator::createToken($header, $payload, 'secret');
        $this->assertTrue(JWTFacilitator::tokenIsExpired($token, 'secret'));
    }

}