<?php
/**
 * Created by PhpStorm.
 * User: dilsonrabelo
 * Date: 13/09/16
 * Time: 17:55
 */

namespace Tests\Facilitator;

use App\Facilitator\App\ContainerFacilitator;
use App\Facilitator\Database\DatabaseFacilitator;
use Doctrine\ORM\EntityManager;
use Illuminate\Database\Capsule\Manager;
use Interop\Container\ContainerInterface;
use Slim\Collection;
use Tests\BaseUnitTests;

class FacilitatorTest extends BaseUnitTests
{

    /**
     * @inheritDoc
     */
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function shouldInstanceContainerInterface() {
        $container = ContainerFacilitator::getContainer();

        $this->assertInstanceOf(ContainerInterface::class, $container);

        $database = DatabaseFacilitator::getConnection();
        $this->assertInstanceOf(Manager::class, $database);
    }

}